name: Rocket

params:
  c_in: 1
  seq_len: 500
  n_kernels: 1000
  kss: [7, 9, 11]
  device: 'cuda:1'
  verbose: False

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: True
