slice: False
save_path: checkpoints/${dataset.name}/${model.name}/${exp_name}/
test_run: False # If true results will be not saved!!!!
exp_name: 'test'

# model_id_start: 100
# model_id_finish: 101
model_id: 100

batch_size: 64
cuda: 'cuda:1'
print_every: 1

train_self_supervised: True

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      ++model_id: 0,1

defaults:
 - model: PatchTST
 - dataset: FordA

transform_data: []
# - _target_: tsai.data.transforms.TSRandomResizedCrop
#   magnitude: 0.1

training_params:
  model_name: ${model.name}
  model_params: ${model.params}
  criterion_name: BCELoss
  criterion_params: None
  optimizer_name: Adam
  optimizer_params:
    lr: 0.0001
  scheduler_name: StepLR
  scheduler_params:
    step_size: 30
    gamma: 0.8
  n_epochs: 3
  early_stop_patience: 50


enable_optimization: False
optuna_optimizer:
  n_trials: 5
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 0
  pruner:
    _target_: optuna.pruners.MedianPruner
  hyperparameters_vary:
    model_name:
      optuna_type: const
      value: ${model.name}
    model_params: ${model.hyperparameters_vary}
    criterion_name:
      optuna_type: const
      value: BCELoss
    criterion_params:
      optuna_type: const
      value: None
    optimizer_name:
      optuna_type: choice
      choices:
        - Adam
        - AdamW
    optimizer_params:
      lr:
        optuna_type: float
        low: 0.0001
        high: 0.01
        log: True
    scheduler_name:
      optuna_type: const
      value: StepLR
    scheduler_params:
      optuna_type: const
      value:
        step_size: 10
        gamma: 0.5
    n_epochs:
      optuna_type: int
      low: 5
      high: 15
    early_stop_patience:
      optuna_type: const
      value: None
