name: PatchTST

params:
  seq_len: 500
  c_in: 1 
  c_out: 1 
  pred_dim: 1 
  n_layers: 2 
  n_heads: 8
  d_model: 512 
  d_ff: 2048 
  dropout: 0.05 
  attn_dropout: 0.0
  patch_len: 16 
  stride: 8 
  padding_patch: True 
  revin: True
  affine: False 
  individual: False 
  subtract_last: False
  decomposition: False 
  kernel_size: 25 
  activation: 'gelu'
  norm: 'BatchNorm' 
  pre_norm: False 
  res_attention: True
  store_attn: False

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: True
