name: RNNA

params:
  seq_len: 50
  c_in: 1 # по умолчанию
  c_out: 1 # по умолчанию
  hidden_size: 128
  rnn_layers: 1 
  bias: True 
  rnn_dropout: 0
  bidirectional: False  
  encoder_layers: 3 
  n_heads: 16
  d_ff: 256 
  encoder_dropout: 0.1 
  act: 'gelu'
  fc_dropout: 0.0

hyperparameters_vary:
  rnn_dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1
  fc_dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: True