_target_: src.models.RNNAttention.RNNA
seq_len: 50
# c_in: 1 # по умолчанию
# c_out: 1 # по умолчанию
# hidden_size: 128
# rnn_layers: 1 
# bias: True 
# rnn_dropout: 0
# bidirectional: False  
# encoder_layers: 3 
# n_heads: 16
# d_ff: 256 
# encoder_dropout: 0.1 
# act: 'gelu'
# fc_dropout: 0.0