name: TST

params:
  seq_len: 50
  c_in: 1 # по умолчанию
  c_out: 1 # по умолчанию
  max_seq_len: None
  d_model: 128
  n_heads: 16
  d_k: 32
  d_v: 32
  d_ff: 256
  dropout: 0.1
  activation: ‘gelu’
  n_layers: 3
  fc_dropout: 0

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: True
