attack_run:
  attack:
    attack_params:
      eps:
      - 0.005
      - 0.1
      - 0.03
      n_steps: 50
    hyperparameters_vary:
      eps:
        high: 0.5
        log: true
        low: 0.01
        optuna_type: float
      n_steps:
        optuna_type: const
        value: 50
    name: FGSMAttack
    short_name: fgsm_attack
  attack_model:
    attack_train_mode: false
    hyperparameters_vary:
      dropout:
        high: 0.7
        low: 0.1
        optuna_type: float
        step: 0.1
    name: TST
    params:
      c_in: 1
      c_out: 1
      d_ff: 256
      d_k: 32
      d_model: 128
      d_v: 32
      dropout: 0.1
      fc_dropout: 0
      max_seq_len: null
      n_heads: 16
      n_layers: 3
      seq_len: ${dataset.seq_len}
  batch_size: 64
  criterion_name: BCELoss
  criterion_params: null
  cuda: cuda:3
  dataset:
    name: PowerCons
    num_classes: 2
    seq_len: 144
    test:
      max: 6.002890636747172
      mean: -0.010892417367795152
      min: -1.0250395745248067
      object_count: 180
      roughness: 0.1544105925399531
    total_object_count: 360
    train:
      max: 6.150072421276428
      mean: -1.7736155479814228e-16
      min: -0.9882441283924925
      object_count: 180
      roughness: 0.15408237025050991
  disc_model_check:
    attack_train_mode: false
    hyperparameters_vary:
      dropout:
        high: 0.7
        low: 0.1
        optuna_type: float
        step: 0.1
    name: TST
    params:
      c_in: 1
      c_out: 1
      d_ff: 256
      d_k: 32
      d_model: 128
      d_v: 32
      dropout: 0.1
      fc_dropout: 0
      max_seq_len: null
      n_heads: 16
      n_layers: 3
      seq_len: ${dataset.seq_len}
  disc_model_reg:
    attack_train_mode: false
    hyperparameters_vary:
      dropout:
        high: 0.7
        low: 0.1
        optuna_type: float
        step: 0.1
    name: TST
    params:
      c_in: 1
      c_out: 1
      d_ff: 256
      d_k: 32
      d_model: 128
      d_v: 32
      dropout: 0.1
      fc_dropout: 0
      max_seq_len: null
      n_heads: 16
      n_layers: 3
      seq_len: ${dataset.seq_len}
  disc_path: results/${dataset.name}/${attack_model.name}/discriminator/fgsm_attack_MODE
  enable_optimization: false
  estimator_batch_size: null
  exp_name: _MODE
  list_check_model_params:
  - model_id: ${model_id_attack}
    model_name: fgsm_attack_eps=0.03_nsteps=10
  metric_effect: F1
  metric_hid: ROC_AUC_DISC
  model_folder: checkpoints/${dataset.name}
  model_id_attack: 0
  optuna_optimizer:
    hyperparameters_vary: ${attack.hyperparameters_vary}
    n_trials: 5
    pruner:
      _target_: optuna.pruners.MedianPruner
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 0
  save_path: results/${dataset.name}/${attack_model.name}/attack/${attack.short_name}${exp_name}
  slice: false
  test_run: false
  use_disc_check: true
timestamp: '2024-06-28 12:12:31'
