name: FGSMRegDiscAttack
short_name: fgsm_disc_attack

attacks_params:
  eps: [0.03] #[0.005, 0.001, 0.03, 0.07, 0.1, 0.13]
  n_steps: 10
  alpha: [0.001] #[10, 1, 100, 0.01, 0.0001, 0.001, 0.1]
  use_sigmoid: False

list_reg_model_params:
  - model_id : 0
    model_name: fgsm_attack_eps=0.03_nsteps=10
  # - model_id: 0
  #   model_name: 'fgsm_disc_attack2_eps=0.03_alpha=10_nsteps=10'  
  # - model_id: 1
  #   model_name: 'fgsm_disc_attack2_eps=0.03_alpha=1_nsteps=10'
  # - model_id: 1
  #   model_name: 'fgsm_disc_attack2_eps=0.03_alpha=10_nsteps=10'  
  # - model_id: 2
  #   model_name: 'fgsm_disc_attack2_eps=0.03_alpha=1_nsteps=10'
  # - model_id: 2

hyperparameters_vary:
  eps:
    optuna_type: float
    low: 0.01
    high: 0.5
    log: True
  n_steps:
    optuna_type: const
    value: 50
  alpha:
    optuna_type: float
    low: 0.01
    high: 0.5
    log: True