name: FGSMAttack
short_name: fgsm_attack

attack_params:
  eps: [0.005, 0.001, 0.03, 0.07, 0.1, 0.13]
  n_steps: 50

hyperparameters_vary:
  eps:
    optuna_type: float
    low: 0.01
    high: 0.5
    log: True
  n_steps:
    optuna_type: const
    value: 50