dataset: FordA  
slice: False
use_disc_check: True
test_run: False # If true results will be not saved!!!!

model_folder: checkpoints/${dataset}/ResCNN/
disc_path: results/${dataset}/IFGSM
save_path: ${disc_path}/${attack_type}_without_sig

model_id_attack: 0

attack_model:
  _target_: src.models.ResidualCNN.ResidualCNN #src.models.TS2VecClassifier 

# attack_model:
#   _target_: src.models.LSTM_net
#   hidden_dim: 50
#   n_layers: 1
#   output_dim: 1
#   dropout: 0.0

disc_model:
  _target_: src.models.ResidualCNN.ResidualCNN #src.models.TS2VecClassifier 
  # dropout: 0.0
  # device: 3
  # n_layers: 2


disc_model_check:
  _target_: src.models.ResidualCNN.ResidualCNN #src.models.TS2VecClassifier 
  # dropout: 0.0
  # device: 3
  # n_layers: 2

cuda: 'cuda:3'

attack_type: fgsm_attack #fgsm_disc_attack
n_iterations: 30
all_eps: [0.001, 0.002, 0.003, 0.004, 0.005] #[0.001, 0.005, 0.0316, 0.1778, 1.0 ]  #  #[0.001, 0.01, 0.05, 0.2, 1.]
train_mode: False
batch_size: 64

alphas: [0.001, 0.01, 0.1, 1, 5, 10, 50, 100]

disc_check_params: 
  model_id : 0
  model_name: 'fgsm_attack/ResCNN/fgsm_attack_eps=0.01_nsteps=10' 

list_reg_model_params: ### поставить другую директорию, для кажждой директории обучить дискриминатор с разными параметрами
 - model_id: 0
   model_name: 'fgsm_attack/ResCNN/fgsm_attack_eps=0.01_nsteps=10' 
#  - model_id: 0
#    model_name: 'fgsm_reg_attack/ResCNN/fgsm_reg_attack_eps=0.03_alpha=100_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_reg_attack/ResCNN/fgsm_reg_attack_eps=0.005_alpha=0.01_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_reg_attack/ResCNN/fgsm_reg_attack_eps=0.005_alpha=0.1_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_disc_attack_new/ResCNN/fgsm_disc_attack_eps=0.005_alpha=0.01_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_disc_attack_new/ResCNN/fgsm_disc_attack_eps=0.005_alpha=0.1_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_disc_attack_new/ResCNN/fgsm_disc_attack_eps=0.005_alpha=1_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_disc_attack_new/ResCNN/fgsm_disc_attack_eps=0.005_alpha=10_nsteps=10'
#  - model_id: 0
#    model_name: 'fgsm_disc_attack_new/ResCNN/fgsm_disc_attack_eps=0.005_alpha=100_nsteps=10'









