dataset: FordA
slice: True
use_disc_check: True
test_run: False # If true results will be not saved!!!!
exp_name: '_NEW_CODE'

model_folder: checkpoints/${dataset}
disc_path: results/${dataset}/${attack_model.name}/discriminator/fgsm_attack
save_path: results/${dataset}/${attack_model.name}/attack/${attack.short_name}${exp_name}

model_id_attack: 0

defaults:
  - model@attack_model: LSTM
  - model@disc_model_reg: LSTM
  - model@disc_model_check: LSTM
  - attack: FGSMDiscSmoothMax

criterion_name: BCELoss
criterion_params: null

batch_size: 128
estimator_batch_size: 32
cuda: 'cuda:1'

metric_effect: F1
list_check_model_params:
  - model_id : 0
    model_name: fgsm_attack_eps=0.03_nsteps=10


enable_optimization: False
optuna_optimizer:
  n_trials: 5
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 0
  pruner:
    _target_: optuna.pruners.MedianPruner
  hyperparameters_vary:
    ${attack.hyperparameters_vary}
    
