dataset: FordA
slice: True
use_disc_check: False
test_run: False # If true results will be not saved!!!!
exp_name: '_LSTM_NEW'

model_folder: checkpoints/${dataset}
disc_path: results/${dataset}/${attack_model.name}/discriminator/fgsm_attack
save_path: results/${dataset}/${attack_model.name}/discriminator/${attack.short_name}${exp_name}
model_id_attack: 0

defaults:
  - model: LSTM
  - model@attack_model: LSTM
  - model@disc_model_reg: LSTM
  - model@disc_model_check: LSTM
  - attack: FGSMDisc

criterion_name: BCELoss
criterion_params: null

metric_effect: F1

batch_size: 64
cuda: 'cuda:1'

list_check_model_params:
  - model_id : 0
    model_name: fgsm_attack_eps=0.03_nsteps=10

transform_data: []
# # - _target_: tsai.data.transforms.TSRandomResizedCrop
# #   magnitude: 0.1

training_params:
  model_name: ${model.name}
  model_params: ${model.params}
  criterion_name: BCELoss
  criterioin_params: null
  optimizer_name: Adam
  optimizer_params:
    lr: 0.001
  scheduler_name: StepLR
  scheduler_params: 
    step_size: 10
    gamma: 0.5
  n_epochs: 15
  print_every: 1
  early_stop_patience: null

      
