dataset: GunPointOldVersusYoung  
slice: True
save_path: checkpoints/${dataset}/TS2Vec

model_id_start: 1
model_id_finish: 5

print_every: 1

TS2Vec: True
model:
  _target_: models.models.TS2VecClassifier
  # hidden_dim: 128
  # n_layers: 1
  # output_dim: 1
  # dropout: 0.3


cuda: 'cuda:2'

batch_size: 64
lr: 0.0001
step_size: 9
gamma: 0.01
n_epochs: 7