dataset: Ford_A_LSTM #GunPoint  
slice: True
save_path: checkpoints/${dataset}
test_run: True # If true results will be not saved!!!!

model_id_start: 0
model_id_finish: 5

print_every: 1

transform_data: 
- _target_: tsai.data.transforms.TSRandomResizedCrop
  magnitude: 0.1

#TS2Vec: False
defaults:
  - model: LSTM

cuda: 'cuda:2'

batch_size: 256
lr: 0.001
step_size: 10
gamma: 0.5
n_epochs: 10